# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build Project

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - run: npm ci

    - run: npm run build
    
    # Start the app in the background
    - name: Start the app in the background
      run: npm run start &
    
    # Wait for the app to be available on port 3000
    - name: Wait for the app to be ready
      run: npx wait-on http://localhost:3000

    # Check if the app is up by making a request
    - name: Health check
      run: curl -f http://localhost:3000 || exit 1

    # - run: npm test